# Dylan's .bashrc

# Set the prompt.
# $USER ~/path/to/dir >
export PS1="$USER \w \[$(tput setaf 5)\]> \[$(tput sgr0)\]"

# Add ~/bin to path
PATH="$HOME/bin:$PATH"

# Set XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME/.config"

export NVM_DIR="/home/alexander/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Source colors generated by wal.
source "$HOME/.cache/wal/colors.sh"

# ALIASES

alias steam="steam-native"
alias sxiv="sxiv -b -s f"

# Import colorscheme from 'wal'
wal -r

